[package]
name = "fileman"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "756fcd0733d7215e591bc21a520ee823f34038c1" }
#gpui = { path = "../zed/crates/gpui" }
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
profiling = "1"
