name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test

  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build snapshot
        env:
          RUSTFLAGS: "--cfg gles"
        run: cargo run -- --snapshot /tmp/screen.png
      - name: Compare snapshot
        run: |
          test -f etc/snapshots/linux.png
          sha256sum /tmp/screen.png etc/snapshots/linux.png
          cmp -s /tmp/screen.png etc/snapshots/linux.png
